### ISSUE TITLE
Variation and Repeats are now two separate options for 'group' (galaxy 101)

### ISSUE THREAD

**Issue by Michael-Xie** [kellrott/galaxy-tooldev-docs#10]
https://usegalaxy.org/u/aun1/p/galaxy101

outdated screenshot

**Comment by Michael-Xie** [comment]
'track' is outdated too

**Comment by lydiayliu** [comment]
the SNPs(131) option no longer exists as well

used All SNPs(138) instead (same position on chr22)

**Comment by kellrott** [comment]
@dannon is working on a new version of the Galaxy 101 video. We'll be replacing it soon.
