### ISSUE TITLE
3.5.1 - Google Cloud Engine

### ISSUE THREAD

**Issue by Michael-Xie** [kellrott/galaxy-tooldev-docs#13]
**Issue**: I made the project on the web console, then I set the project in the command-line, however, it gave me this error:
NAME PROJECT ALIAS DEPRECATED STATUS
ERROR: (gcloud.compute.images.create) Some requests did not succeed:
- Access Not Configured. The API (Compute Engine API) is not enabled for your project. Please use the Google Developers Console to update your configuration.

_Might be good to provide more direction if this occurs often._

**Issue**: Instruction is confusing because it first instructs the user to go to the GCE quick start, yet at the same time provide the instructions on the web page. An example can be seen below:

At this point you may need to add a firewall rule set to allow traffic to the HTTP port (80). Instructions about this can be found in the GCE quick start manual.

The command to add a HTTP ruleset is (note that we are assigning the tagset name 'http-server', this will be reference later when we create an VM instance that uses these firewall rules):

**Issue**: Spelling 
~Example~: Remember when you are done using your VM, turn it off. You are ~~changed~~ **charged** for every hour it is on, and if you forget about it, it will rack up costs quickly.
~Example~: Recheck **Updating Planemo Image**

**Issue**: To deploy via the web interface
Is there a web interface way to resolve the page not loading after clicking on IP address (step 8)?

**Issue**: Transferring data between instances
I am confused on how transfer between local machine and original machine is related to transferring between instances. 

Also, does original machine have the same meaning as VM (virtual machine)?

**Comment by kellrott** [comment]
These issues have been mostly addressed in recent patches
