### ISSUE TITLE
Loading the Planemo Image

### ISSUE THREAD

**Issue by srinivasans** [kellrott/galaxy-tooldev-docs#14]
I tried this command to load planemo-machine-image in my project, but the resource access is denied.

gcloud compute images create planemo-machine-image --source-uri http://storage.googleapis.com/galaxyproject_images/planemo_machine.image.tar.gz

NAME PROJECT ALIAS DEPRECATED STATUS
ERROR: (gcloud.compute.images.create) Some requests did not succeed:
- Required 'read' permission for 'http://storage.googleapis.com/galaxyproject_images/planemo_machine.image.tar.gz'

**Comment by dannon** [comment]
Thanks for the report!  Try again now and it should work.

**Comment by kellrott** [comment]
Fixed
