### ISSUE TITLE
Remind users to enable API for project

### ISSUE THREAD

**Issue by lydiayliu** [kellrott/galaxy-tooldev-docs#16]
After setting the project ID in 3.5.1 under **To start up the Planemo Machine under GCE**, if the user just proceeds to "Set your default zone", or **Loading the Planemo Image**, this error would occur:

> NAME PROJECT ALIAS DEPRECATED STATUS
> ERROR: (gcloud.compute.images.create) Some requests did not succeed:
> 
>    Access Not Configured. The API (Compute Engine API) is not enabled for your project. Please >use the Google Developers Console to update your configuration.

To resolve this please remind the user before these steps to 
1. go to the webpage "Google Developers Console" at https://console.developers.google.com/project
2. choose the project
3. Under APIs, choose Compute Engine API  and "Enable"

This part is missing from the google manual also.

**Comment by kellrott** [comment]
This should be addressed in https://github.com/kellrott/galaxy-tooldev-docs/commit/8b00fd45b6194a93a724d84f413e8270dcfb28e2
