### ISSUE TITLE
Command for stoping VM in GCE

### ISSUE THREAD

**Issue by lydiayliu** [kellrott/galaxy-tooldev-docs#17]
In 3.5.1 under **Starting VM instance via command line**, the "To deply via command line interface" line can be changed to "To create and start running the planemo instance via command line interface", or else the user might not realize that this command CREATES and STARTS the new instance.

Also under 

> Remember when you are done using your VM, turn it off. You are charged for every hour it is on, and if you forget about it, it will rack up costs quickly.

It would be helpful to include the command on how to stop the instance planemo (and at the same time remind the user that it is running at the moment)
    'gcloud compute instances stop planemo'

**Comment by kellrott** [comment]
Fixed in https://github.com/kellrott/galaxy-tooldev-docs/commit/647914349c9cfb154e1c2ed127b77ef7e29e27d5
