### ISSUE TITLE
Update Starting VM instance via the web interface

### ISSUE THREAD

**Issue by lydiayliu** [kellrott/galaxy-tooldev-docs#18]
The interface for creating VM instance via the web has changed.

The instructions written in 3.5.1 under **Starting VM instance via the web interface** is still mostly correct, but the image can be updated.

Also 5.5. can be updated to "For the Boot Disk, select "Your image", then "'planemo-machine-image'"
Discard 5.6.

![gce instance](https://cloud.githubusercontent.com/assets/10492815/7612042/3647752c-f956-11e4-98d7-6fe670fd6b31.png)

**Comment by kellrott** [comment]
This should be fixed in https://github.com/kellrott/galaxy-tooldev-docs/commit/0976dab3e4b74176e0de32488e7597a84506d76e
