### ISSUE TITLE
planemo --galaxy_root /opt/galaxy/galaxy-app/ t command

### ISSUE THREAD

**Issue by mjko1210** [kellrott/galaxy-tooldev-docs#2]
It didn't work when 't' was after the galaxy_root. It worked with 'planemo t --galaxy_root=/path/to/galaxy'.
Also, my galaxy_root was '/opt/galaxy/galaxy-app/' instead of '/opt/galaxy'. I had to find the directory where run_tests.sh exists.

**Comment by kellrott** [comment]
Is this still a bug? I know @jmchilton was fixing some things in the image.

**Comment by jmchilton** [comment]
@kellrott the recipe now builds with a pre-specified root (https://github.com/galaxyproject/planemo-machine/commit/8cc5c95b5a4a2b9db882f82a28cda9e306150a0d). I think we would need to build a GCE image, etc... for this to be propagated because I believe I added this after the latest build.

**Comment by kellrott** [comment]
We need to push a new image to take care of issue fixed in https://github.com/galaxyproject/galaxy/pull/45
I've added some text about updating by creating a new VM to the docs. But that section will probably need a bit more text.

**Comment by kellrott** [comment]
The new image has been pushed and docs about how to do an update have been added
