### ISSUE TITLE
Vagrant Based Development

### ISSUE THREAD

**Issue by srinivasans** [kellrott/galaxy-tooldev-docs#21]
Instructions for installation of image not clear. 

Error with the command.

```
vagrant up
```

> No usable default provider could be found for your system.
> 
> Vagrant relies on interactions with 3rd party systems, known as
> "providers", to provide Vagrant with resources to run development
> environments. Examples are VirtualBox, VMware, Hyper-V.
> 
> The easiest solution to this message is to install VirtualBox, which
> is available for free on all major platforms.
> 
> If you believe you already have a provider available, make sure it
> is properly installed and configured. You can see more details about
> why a particular provider isn't working by forcing usage with
> `vagrant up --provider=PROVIDER`, which should give you a more specific
> error message for that particular provider.

**Comment by lydiayliu** [comment]
Had the same issue. Could be resolved by following the above suggestion and installing VirtualBox.

After installation of VirtualBox, running "vagrant up" adds box "planemo" from the link provided. (Takes a long time)

**Comment by kellrott** [comment]
This should be taken care of in https://github.com/kellrott/galaxy-tooldev-docs/commit/bb937261e33797cc4798a9c7b3f0a82d9ffffb26
