### ISSUE TITLE
Typo in 3.5.2 - Vagrant

### ISSUE THREAD

**Issue by lydiayliu** [kellrott/galaxy-tooldev-docs#23]
In 3.5.2 under **Vagrant Based Development**, the end of the first paragraph should be "provided".

> As an alternative to the Google Cloud based development kit, it is possible to run the Planemo SDK on your personal machine. For the purposes of the SMC-Het challenge, we provide this as an alternative but encourage contestants to use Google Cloud VMs and take advantage of the free compute credits provide.

**Comment by kellrott** [comment]
Fixed in https://github.com/kellrott/galaxy-tooldev-docs/commit/40e68e879d36ac6198b38a50cd6ac058c38a34d4
