### ISSUE TITLE
Typo in 3.5.3 - Docker

### ISSUE THREAD

**Issue by lydiayliu** [kellrott/galaxy-tooldev-docs#24]
1. In 3.5.3, under **Developing a Docker Container**, the first paragraph is:

> To run an analysis tool in a cloud compute environment, all of the dependencies and environmental configurations that are need for running the code need to be packaged us so they can be transported. For this reason we use Docker to describe the tool environment.

In "running the code need to be packaged **us** so they can be transported", I believe the "us" is a typo, or there are some missing words in that sentence.
1. The second paragraph has the line

> For this to work here needs to be a "Dockerfile" 

It should be _there needs to be_
1. The 4th paragraph has

> Any of the images found at the Registry and be used as a basis of builds.

Should be _can be used_

**Comment by kellrott** [comment]
Fixed in https://github.com/kellrott/galaxy-tooldev-docs/commit/1d98b146e60255d574d1cee4950b8be1071b3725
