### ISSUE TITLE
Formating and Typo in 3.5.5 - Working With Examples

### ISSUE THREAD

**Issue by lydiayliu** [kellrott/galaxy-tooldev-docs#25]
1 . In 3.5.5, under **Working on Examples**, the first paragraph is

> These examples are based on being able to access a terminal on the planemo machine and work in the /opt/galaxy/tools directory. If you don't know how to do this, fix the instructions on how to SSH into your system. You will want to execute these commands as the ubuntu user.

the "/opt/galaxy/tools" should be displayed with the format like code, now it is like normal text so it is very easy to miss

2 . Under **Download example code**, point 3. should be corrected to _on the left hand side of the screen_

3 . Also under **Download example code**, there is "Because of this, the "DPC" program from the smchetexample package should appear in the left hand side of the window."

First it should be "VCF DPC VCF clustering" tool. 
Also I don't know what "smchetexample" is supposed to be.

**Comment by kellrott** [comment]
This should be fixed in https://github.com/kellrott/galaxy-tooldev-docs/commit/f63687beaea31c7580a172cf20be89789a59903e and https://github.com/kellrott/galaxy-tooldev-docs/commit/8a1e6b776fe3e2811ed685ad2f079bf3dcf2c742
