### ISSUE TITLE
Poor Instructions in "Using the DPC code"

### ISSUE THREAD

**Issue by lydiayliu** [kellrott/galaxy-tooldev-docs#26]
In 3.5.5, under **Using the DPC code**, the instructions are very unclear.
1. "Hitting the upload button" is very simplified of an instruction, as there is no "upload button" (plus there is a typo in "to you instance"). Can be changed to _Upload test data to your instance by selecting 'Get Data', 'Upload File', then selecting 'Paste/Fetch Data' and telling galaxy to download the file from the following url_

> You can upload test data to you instance by hitting the upload button, selecting 'Paste/Fetch Data' and telling galaxy to download the file
1. The points of instructions underneath the above line is very unclear in whether they are for "using the DPC code", or for uploading the data file...
   Maybe add another line above those such as _To execute the DPC code on the sample data:_

**Comment by kellrott** [comment]
Added picture of the upload button in https://github.com/kellrott/galaxy-tooldev-docs/commit/578cfeaa358f8124cef0d24b11e4dcae04aac463
