### ISSUE TITLE
Missing Link and Typo in 3.5.4 - Tool Wrapper Syntax

### ISSUE THREAD

**Issue by lydiayliu** [kellrott/galaxy-tooldev-docs#27]
1 . In 3.5.4 under **Tool Wrapper Scripts and Parameter Files**, there is a line with a missing link from under it

> The example for the DPC code would be the:
> 
> Wrapper XML File:
> https://github.com/Sage-Bionetworks/SMC-Het-Challenge

2 . In "Each tool wrapper configuration includes", point 3. should be _Input files and parameters_

3 . Under **Tool Wrapper Stanzas**, point 5. should be _All of the files that will be outputted by the program_

4 . Formatting issue under **Declaring Input Parameters**
![formatting issue](https://cloud.githubusercontent.com/assets/10492815/7618596/22c97452-f981-11e4-86f0-2d7809cbf7b4.png)

5 . Under **Writing Command line templates** last paragraph, "additional task such file and config setup as well as" should be _additional tasks such as file and config setup as well as_

**Comment by kellrott** [comment]
These issues should be taken care of in https://github.com/kellrott/galaxy-tooldev-docs/commit/0976dab3e4b74176e0de32488e7597a84506d76e
