### ISSUE TITLE
Error in using DPC code

### ISSUE THREAD

**Issue by lydiayliu** [kellrott/galaxy-tooldev-docs#28]
When following the instructions in 3.5.5 under **Using the DPC code**, step 3, the following error message is outputted in Galaxy:

> time="2015-05-13T19:19:32Z" level=fatal msg="Post http:///var/run/docker.sock/v1.18/containers/create: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?"

All 5 datasets encounter the same error and cannot be executed.

Environment: ubuntu@planemo on GCE

**Comment by lydiayliu** [comment]
Docker does not work on GCE instances created from the provided planemo-machine-image

> ubuntu@planemo:~$ sudo docker run hello-world
> FATA[0000] Post http:///var/run/docker.sock/v1.18/containers/create: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 

Running the example in https://docs.docker.com/installation/google/ using the provided image allows proper running of 

> sudo docker run hello-world

**Comment by kellrott** [comment]
I had a similar experience as well. It cleared after I ran 

```
sudo service docker restart
```

But Docker should work from first boot...

**Comment by kellrott** [comment]
The issue has been fixed: https://github.com/galaxyproject/planemo-machine/commit/fd6b22a5def308b5b8f3a0cdc69fedfa45a07e2d
An updated version of the VM will be built
