### ISSUE TITLE
Formating and Typo in 3.5.7 - Submitting Code

### ISSUE THREAD

**Issue by lydiayliu** [kellrott/galaxy-tooldev-docs#29]
1 . Under **Submitting a workflow to the SMC-Het Challenge** last section point 1. the formatting is strangely italicized.
![screenshot from 2015-05-13 15 27 19](https://cloud.githubusercontent.com/assets/10492815/7619116/9ae0706e-f984-11e4-9f03-0517472e9fe1.png)

2 . Under **Creating a Workflow** in the first paragraph there is

> right hand side or the first tool

Should be _right hand side of the first tool_

3 . Under **Submit the workflow**, first step, point 3. there is

> When the dropdown menu appears select 'Share of Publish'

Should be _Share or Publish_

**Comment by dannon** [comment]
Looks like we need to escape the _ here.

**Comment by kellrott** [comment]
This should be fixed in https://github.com/kellrott/galaxy-tooldev-docs/commit/d76236270bae0cce30650ef837e716942a0533b3
