### ISSUE TITLE
Need more documentation on running tools

### ISSUE THREAD

**Issue by mjko1210** [kellrott/galaxy-tooldev-docs#4]
It took me  a while to figure out how to link input data on docker (xml) file.

In DPC example, I indicated input vcf file with  `<param name="input_vcf" value="mutect_filtered_IS3_chr21.vcf"/>` inside of `<test>`.

Plus, I had to copy the input data into 'test-data' folder by creating a new one which is in the same directory with dpc.xml. 
## Test was passed.

All 1 test(s) executed passed.
## dpc[0]: passed

With job standard output from 'tool_test_output.html':
[1] "num.muts=134"
[1] 100
[1] 200
[1] 300
[1] 400
[1] 500
[1] 600
[1] 700
[1] 800
[1] 900
[1] 1000
[1] "density.smooth=0.1"
[1] "No mutationCopyNumber. Using mutation burden"
[1] "highest density is at 0.103326810176125"

I think it run completely without an error but I didn't get other outputs like png and txt files.
Do I have to indicate output as well inside of dpc.xml?

Thanks,
Minjeong

**Comment by kellrott** [comment]
Is this from running the planemo unit testing? 
Because you mention using the tool-data directory, I'm assuming that you followed tool testing instructions? I think the unit testing automatically cleans up and removes the results after a successful test. If you actually want to run the tool and inspect the results, you need to use the web ui.

**Comment by mjko1210** [comment]
I chose vagrant based development and followed tool development procedure described in `https://www.synapse.org/#!Synapse:syn2786217/wiki/209797`. After that, I run tools using `planemo --galaxy_root=/path/to/galaxy t`. So you didn't cover the section for running tools using the web ui yet? I couldn't find any other option for running tools except that planemo command.

**Comment by kellrott** [comment]
The assumption was that people would log into the web site once it was launched. I guess a intro chapter about how to use the Galaxy UI needs to be added.

**Comment by mjko1210** [comment]
That would be good! Some of people will not be familiar with galaxy UI.

**Comment by kellrott** [comment]
I've added a new section with links to tutorials and videos from the Galaxy community ( https://www.synapse.org/#!Synapse:syn2786217/wiki/213548 )
