### ISSUE TITLE
Google cloud testing 

### ISSUE THREAD

**Issue by canghel** [kellrott/galaxy-tooldev-docs#5]
I have a lot of problems with the testing, and it is very frustrating and time-consuming.  Here are some of my suggestions/issues:
- In the "Getting Started" section, the mention of Docker in Planemo-Machine and then again for the VM system of choice is confusing, since Docker intructions are now omitted for the VM machine, but this is not mentioned.  Please add a sentence after the current depolyment options to mention that Docker is for more advanced users and that the following instructions are for the Google Cloud Engine and for Vagrant.
- For the page connecting to the "Google Developers Console" and the main steps of the procedure, it is not clear which steps I should do.  In particular:
  - I assume "Setting up ssh keys" in the "Google Developers Console" page can be skipped?
  - Does "2) create an instance and attach the disk" mean "Attaching a non-root persistent disk"? (I don't know what using a root persistent disk means).
- I could execute "gcloud auth login" and "gcloud config set project SMCtest" but I cannot see that project in the web interface, at https://console.developers.google.com .  Why is that?
- A note on the difference between project name and project id would be useful. 
- I went into the web interface, made a new project and clicked inside, yet when I went into Compute -> Compute Engine -> VM Instances, it asks me to "Sign up for a free trial" although the email that we're using, boutroslabgce@gmail.com, has a billing address attached. (Nicole asked us to make one account, so all of us at OICR are using this account, and trying to make our own test projects separately in it.)

Thank you.

**Comment by canghel** [comment]
Sorry, the last point was because we paid to the wrong account.  :(

**Comment by dannon** [comment]
Thanks for this feedback!  I'll try to get the docs updated today.

**Comment by kellrott** [comment]
I've removed the reference about docker and moved the GCE and VirtualBox instructions into their own sections. 

We should probably point out that the link to the instructions at "Google Developers Console" are for reference and should lead to a whole other set of steps. I think what we have on the page will work by itself.

I've added instructions on the GCE page about how to create a volume (for permanent storage), but not yet the bit about how to mount it in the OS. (@dannon do you have any ideas about the best way to format/mount a volume without telling them to start editing the fstab?)

I think it needs to be "gcloud config set project PROJECT-ID", I'm assuming 'SMCtest' is the project name. Maybe a screen shot to help people on the difference between the two?
