### ISSUE TITLE
GCE-test

### ISSUE THREAD

**Issue by mjko1210** [kellrott/galaxy-tooldev-docs#6]
1) How to create project? using command-line or from the development console?

At first, I thought 'gcloud config set project' command will create a new project but I couldn't see it from the console. To get the Project-ID, using the console by clicking 'create project' seems the only way. Is this correct? Couldn't figure it out how to obtain Project-ID by using command.

2)  Need to specify project for `gcloud compute instances create planemo --machine-type n1-standard-2 --image planemo-machine-image --zone us-central1-f --tags http-server`.

As I mentioned above, I created project in two ways : 1) command line `gcloud config set project mjko-test`  2) directly created from the console. 1st approach, I still don't know what's going on but 2nd approach, I can get Project-ID and Project-Number.
When I run the deployment command above, it gave me an error message of `Invalid value for project: mjko-test`. However, it worked after I specified project-id with --project option.

Output:
`gcloud compute instances create planemo --machine-type n1-standard-2 --image planemo-machine-image --zone us-central1-f --tags http-server --project dazzling-card-88816`
NAME    ZONE          MACHINE_TYPE  INTERNAL_IP    EXTERNAL_IP    STATUS
planemo us-central1-f n1-standard-2 10.240.163.180 104.154.64.188 RUNNING

3) Eventually, I could follow the instructions (and run) described in 'https://www.synapse.org/#!Synapse:syn2786217/wiki/160587`. However, I don't know how to run our test example (dpc code) using GCE. I think we need instruction on this.

Thanks,
Minjeong

**Comment by kellrott** [comment]
I've updated the instructions to highlight some of the issues you mentioned. Does  https://www.synapse.org/#!Synapse:syn2786217/wiki/209793 cover the issues a bit better?

**Comment by mjko1210** [comment]
`First go to https://console.developers.google.com to view your projects, and obtain
your project id. If you do not already have a project use the 'Create Project' button.`
In my personal opinion, I don't want people to start with finding/viewing project first. This will make confusion. It's more natural for me to be informed by 'creating project' in the first place. 
Do users usually create their own project or do we assign project for them? Maybe, I don't have clear idea on that. 

Are you going to add one more section for working with example using GCE? I couldn't figure out how to run DPC code using GCE.
