### ISSUE TITLE
GCE deployment docs

### ISSUE THREAD

**Issue by ChrisCooper** [kellrott/galaxy-tooldev-docs#8]
### Google Cloud Engine based Deployment
- 

>  This page is a good short intro/summary of how to use the console:

Might be clearer that it's optional if in parentheses

> (This page is a good short intro/summary of how to use the console.)
- 

> First go to https://console.developers.google.com to view your projects, and obtain
> your project id.

Specifying that you'll need to create a project first to get this would be good.
- 

On running `gcutil --project="exalted-slice-88902" addimage planemo-machine-image http://storage.googleapis.com/galaxyproject_images/planemo_machine.image.tar.gz`, I got these messages: 

> WARNING: 'gcutil' has been deprecated and soon will be removed from Cloud SDK distribution.
> WARNING: Please use 'gcloud compute' instead.
> WARNING: For more information see https://cloud.google.com/compute/docs/gcutil
> Error: Access Not Configured. The API (Compute Engine API) is not enabled for your project. Please use the Google Developers Console to update your configuration.

The warning can be fixed by changing that command I assume? But I'm not sure if that error is because there is a missing step, or if I can ignore it. Either way it should probably be addressed in the docs.
- 

After getting success on the previous command (possibly by opening something in the web console), the command `gcloud compute instances create planemo --machine-type n1-standard-2 --image planemo-machine-image --zone us-central1-f --tags http-server` gave:

> ERROR: (gcloud.compute.instances.create) The required property [project] is not currently set.
> You may set it for your current workspace by running:
> 
>   $ gcloud config set project VALUE
> 
> or it can be set temporarily by the environment variable [CLOUDSDK_CORE_PROJECT]

I assume this was caused by the previous command semi-failing? Anyway, running that command fixed it.

**Comment by ChrisCooper** [comment]
- 

> you can restart the server by sshing into the server and issuing the command

I stopped at this point to try to figure out how to ssh myself. A little note saying "instructions below" would stop that from happening.
- 

Not sure if I'm doing something wrong or not... I'm getting timeouts when trying to connect to the VM:

> $ gcloud compute instances create planemo --machine-type n1-standard-2 --image planemo-machine-image --zone us-central1-f --tags http-server
> Created [https://www.googleapis.com/compute/v1/projects/exalted-slice-88902/zones/us-central1-f/instances/planemo].
> NAME    ZONE          MACHINE_TYPE  INTERNAL_IP    EXTERNAL_IP    STATUS
> planemo us-central1-f n1-standard-2 10.240.127.131 146.148.79.255 RUNNING

And then:

> wget 146.148.79.255
> --2015-03-19 00:29:51--  http://146.148.79.255/
> Connecting to 146.148.79.255:80... failed: Connection timed out.

I tried sshing in and restarting, but it didn't seem to change anything. Could some earlier error have caused this? Here is a screenshot of the console overview.

![screenshot from 2015-03-19 00 50 25](https://cloud.githubusercontent.com/assets/343153/6724635/31675888-cdd2-11e4-96e0-c25268cdd253.png)

**Comment by kellrott** [comment]
Can you go into Compute -> Networks -> default (?) -> and see if the firewall runs have a line like 

NAME    SOURCE TAG / IP RANGE   ALLOWED PROTOCOLS / PORTS   TARGET TAGS
default-allow-http  0.0.0.0/0   tcp:80  http-server

I want to see if you have a network rule to allow traffic on port 80 if you pass in the tag http-server.

**Comment by ChrisCooper** [comment]
I don't see a line like that, no.

![network](https://cloud.githubusercontent.com/assets/343153/6757045/64d2f366-cf04-11e4-9337-c374841a0abf.png)

**Comment by kellrott** [comment]
Ok. It looks like I must have inherited some default configurations that you didn't. We'll need to add some text related to checking for a HTTP security group and then adding one if it is not already there. 
For now, you should just be able to go to the instance and click 'allow http traffic' and then you should be able to contact it

**Comment by kellrott** [comment]
- I've updated the text to clarify that reading the GCE console docs is optional.
- I added a note to use the 'Create a Project' button if no projects exist on the GCE console.
- The gcutil based add image has been replaced with gcloud based instructions

**Comment by ChrisCooper** [comment]
Ok, I didn't see the "allow http traffic" button/link, but adding the rule you described has given me access.

**Comment by kellrott** [comment]
I've added some text related to setting up firewall rules as well as a link to the quick start guide.
