### ISSUE TITLE
Links do not work in Synapse Section 3.5

### ISSUE THREAD

**Issue by Michael-Xie** [kellrott/galaxy-tooldev-docs#9]
https://www.synapse.org/#!Synapse:syn2786217/wiki/74384

"Before any development can happen, you must first deploy a Planemo-Machine in your VM
system of choice. The current deployment options are: **Google Cloud Engine** and
**Virtual Box**."

The links (in bold) do not work.

**Comment by kellrott** [comment]
This should be fixed in https://github.com/kellrott/galaxy-tooldev-docs/commit/0976dab3e4b74176e0de32488e7597a84506d76e
